server:
  port: 8080
spring:
  redis:
    # 连接信息
    host: localhost
    port: 6379
    password:
    database: 0
    # 连接池配置（Lettuce）
    lettuce:
      pool:
        max-active: 8 # 最大连接数
        max-idle: 8 # 最大空闲连接
        min-idle: 1 # 最小空闲连接
        max-wait: 1000ms # 连接等待超时时间
    timeout: 5000ms # 命令执行超时时间
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    minimum-idle: 1
    maximum-pool-size: 5
    auto-commit: true
    idle-timeout: 300000
    pool-name: HikariPool-1
    connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
jwt:
  secret: Y2FzdGxlZmVzdHdlYmNyYWRpbmdyZWV0b21pY2hhZWxkb3VzdGhpc3NlY3JldGtleW11c3RiZXF1aXRlbG9uZ2VybmdhbmR2ZXJ5c2VjdXJl
  expiration-ms: 3600000

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    deep-linking: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false