spring:
  application:
    name: ddd-admin
  profiles:
    active: @activatedProperties@
  threads:
    virtual:
      enabled: true

file:
  storage:
    type: local # local
    local:
      path: ./uploads
      domain: http://localhost:8080
      prefix: /files