server:
  port: 8082
spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/ddd_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  hikari:
    minimum-idle: 5
    maximum-pool-size: 20
    auto-commit: true
    idle-timeout: 300000
    pool-name: HikariPool-1
    connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
jwt:
  secret: Y2FzdGxlZmVzdHdlYmNyYWRpbmdyZWV0b21pY2hhZWxkb3VzdGhpc3NlY3JldGtleW11c3RiZXF1aXRlbG9uZ2VybmdhbmR2ZXJ5c2VjdXJl
  expiration-ms: 3600000
